
import { BrainCircuit, CalendarDays, HeartPulse, Landmark, LucideIcon, Sparkles } from 'lucide-react';

export interface CalculatorInfo {
    value: string;
    label: string;
    path: string;
    category: 'Financial' | 'Health' | 'Date & Time' | 'Math & Science' | 'Other';
    icon: LucideIcon;
    keywords?: string[];
    description?: string;
}

export const allCalculators: CalculatorInfo[] = [
    // Financial
    { value: 'suggestions', label: 'AI Suggestions', path: '/', category: 'Financial', icon: Landmark, keywords: ['finance', 'ai', 'loan', 'optimization'], description: "Unlock personalized strategies to manage your debt with our AI Suggestions calculator. By analyzing your loan amount, interest rate, income, and financial goals, this tool provides actionable advice on how to pay off your loan faster, reduce interest payments, and align your repayment plan with your risk tolerance." },
    { value: 'budget', label: 'Budget', path: '/', category: 'Financial', icon: Landmark, keywords: ['finance', 'expense', 'income', 'money'], description: "Take control of your financial health with our comprehensive Budget Calculator. Track your monthly income sources and categorize your expenses to get a clear overview of your cash flow. Visualize your spending habits with an interactive pie chart and identify areas where you can save. The summary provides a clear net balance, helping you make informed decisions about your money." },
    { value: 'comparison', label: 'Loan Comparison', path: '/', category: 'Financial', icon: Landmark, keywords: ['finance', 'loan', 'compare'], description: "Make smarter borrowing decisions with the Loan Comparison Calculator. Evaluate two different loan scenarios side-by-side to determine the best option for your needs. Compare monthly payments, total interest paid, and overall costs to see which loan saves you more money in the long run." },
    { value: 'compound-interest', label: 'Compound Interest', path: '/', category: 'Financial', icon: Landmark, keywords: ['finance', 'investment', 'savings'], description: "Witness the power of compounding with our Compound Interest Calculator. Project the future value of your investment by inputting your initial principal, monthly contributions, investment period, and expected interest rate. The tool provides a detailed year-by-year breakdown and a growth chart to visualize your money's potential." },
    { value: 'calculator', label: 'EMI Calculator', path: '/', category: 'Financial', icon: Landmark, keywords: ['finance', 'loan', 'payment', 'interest'], description: "Our Equated Monthly Installment (EMI) Calculator helps you understand your loan repayment details. Calculate your monthly payment for any loan and see a full amortization schedule, breaking down each payment into principal and interest. The tool also shows how extra payments can help you save on interest and pay off your loan sooner." },
    { value: 'fd-calculator', label: 'FD Calculator', path: '/', category: 'Financial', icon: Landmark, keywords: ['finance', 'fixed deposit', 'investment'], description: "Plan your secure investments with the Fixed Deposit (FD) Calculator. Estimate the maturity value of your one-time investment based on the principal amount, interest rate, tenure, and compounding frequency. Visualize the growth of your investment over the years." },
    { value: 'gratuity', label: 'Gratuity', path: '/', category: 'Financial', icon: Landmark, keywords: ['finance', 'india', 'retirement', 'salary'], description: "For our users in India, the Gratuity Calculator helps estimate the lump-sum amount you are entitled to receive from your employer after years of service. Based on your last drawn salary and tenure, this tool calculates your estimated gratuity as per the Payment of Gratuity Act." },
    { value: 'gst', label: 'GST', path: '/', category: 'Financial', icon: Landmark, keywords: ['finance', 'tax', 'india', 'goods and services'], description: "Quickly calculate the Goods and Services Tax (GST) for any amount with our simple GST Calculator. Whether the amount is GST-inclusive or exclusive, this tool provides a clear breakdown of the base amount, CGST, SGST, and the total figure, making tax calculations effortless." },
    { value: 'indian-tax', label: 'Indian Tax', path: '/', category: 'Financial', icon: Landmark, keywords: ['finance', 'tax', 'india', 'income'], description: "Navigate the Indian tax system with ease using our Income Tax Calculator for FY 2023-24. Compare your tax liability under both the old and new tax regimes. Input your income and deductions to get a detailed breakdown of your taxable income, tax liability, and effective tax rate." },
    { value: 'investment', label: 'Investment', path: '/', category: 'Financial', icon: Landmark, keywords: ['finance', 'stocks', 'returns'], description: "Project the future of your investments with the Investment Growth Calculator. Whether you're starting with a lump sum, making regular monthly contributions, or both, this tool helps you visualize the potential growth of your portfolio over time based on your expected annual return." },
    { value: 'lumpsum-calculator', label: 'Lumpsum', path: '/', category: 'Financial', icon: Landmark, keywords: ['finance', 'investment', 'one-time'], description: "See how a single, one-time investment can grow over time with our Lumpsum Calculator. Enter your initial investment amount, the expected rate of return, and the investment period to project the future value and see a year-by-year breakdown of its growth." },
    { value: 'mortgage-calculator', label: 'Mortgage', path: '/', category: 'Financial', icon: Landmark, keywords: ['finance', 'home', 'loan', 'property'], description: "Our Advanced Mortgage Calculator gives you a complete picture of your home loan payments. Beyond principal and interest, it accounts for annual property taxes, home insurance, and monthly HOA dues to estimate your total monthly housing expense. A detailed amortization schedule and visual charts are included." },
    { value: 'ppf-calculator', label: 'PPF Calculator', path: '/', category: 'Financial', icon: Landmark, keywords: ['finance', 'provident fund', 'india', 'savings'], description: "Plan your long-term savings with the Public Provident Fund (PPF) Calculator. Estimate the maturity value of your investment after the mandatory 15-year lock-in period. The tool shows your total investment, interest earned, and a yearly breakdown of the balance." },
    { value: 'rd-calculator', label: 'RD Calculator', path: '/', category: 'Financial', icon: Landmark, keywords: ['finance', 'recurring deposit', 'investment'], description: "Calculate the maturity amount of your Recurring Deposit (RD) with our RD Calculator. Based on your monthly deposit, tenure, and interest rate, this tool projects the future value of your disciplined savings, including a detailed growth chart." },
    { value: 'refinance', label: 'Refinancing', path: '/', category: 'Financial', icon: Landmark, keywords: ['finance', 'loan', 'interest', 'savings'], description: "Should you refinance your loan? Our AI-powered Refinancing Analysis tool helps you decide. Compare your current loan with a new offer, factoring in closing costs, to see the potential lifetime savings and changes to your monthly payment. Get a clear 'Recommended' or 'Not Recommended' verdict." },
    { value: 'retirement', label: 'Retirement', path: '/', category: 'Financial', icon: Landmark, keywords: ['finance', 'pension', 'savings', '401k'], description: "Are you on track for a comfortable retirement? Our Retirement Savings Calculator helps you find out. Project your total savings at retirement age and compare it against the nest egg required to fund your desired lifestyle. Identify any potential shortfall or surplus to adjust your strategy today." },
    { value: 'roi', label: 'ROI', path: '/', category: 'Financial', icon: Landmark, keywords: ['finance', 'return on investment'], description: "Measure the efficiency of your investments with the Return on Investment (ROI) Calculator. By comparing the final value of an investment to its initial cost, this tool gives you a clear percentage return, helping you assess the profitability of your financial decisions." },
    { value: 'savings', label: 'Savings', path: '/', category: 'Financial', icon: Landmark, keywords: ['finance', 'goal', 'money'], description: "Define your financial goal and let our Savings Goal Calculator figure out the rest. This tool determines the required monthly savings you need to put aside to reach your target amount within a specified timeframe, factoring in your initial savings and expected investment returns." },
    { value: 'sip-calculator', label: 'SIP Calculator', path: '/', category: 'Financial', icon: Landmark, keywords: ['finance', 'systematic investment plan', 'mutual fund'], description: "Our Advanced SIP (Systematic Investment Plan) Calculator lets you project the future value of your mutual fund investments. It includes an option for an annual step-up, allowing you to increase your investment amount each year and see how it accelerates your wealth creation." },
    { value: 'tax', label: 'US Tax', path: '/', category: 'Financial', icon: Landmark, keywords: ['finance', 'tax', 'usa', 'federal'], description: "Estimate your U.S. federal income tax liability for 2024 with our simple Tax Calculator. Select your filing status and enter your gross income to see your taxable income, total tax due, and effective tax rate based on the latest standard deductions and tax brackets." },

    // Health
    { value: 'age', label: 'Age', path: '/personal-health-calculators', category: 'Health', icon: HeartPulse, keywords: ['health', 'birthday', 'zodiac'], description: "Discover more than just your age with our advanced Age Calculator. Find out your age in years, months, and days, see fun facts like the day of the week you were born on, your zodiac sign, and a countdown to your next birthday. You can also calculate your age at any specific date in the past or future." },
    { value: 'bmi', label: 'BMI', path: '/personal-health-calculators', category: 'Health', icon: HeartPulse, keywords: ['health', 'body mass index', 'weight'], description: "The Body Mass Index (BMI) Calculator is a tool to assess your weight relative to your height. It provides a simple, impartial measure of whether your weight is in a healthy range. Our calculator shows your BMI and the corresponding WHO weight status category to help you understand your results." },
    { value: 'bmr', label: 'BMR', path: '/personal-health-calculators', category: 'Health', icon: HeartPulse, keywords: ['health', 'basal metabolic rate', 'calories'], description: "Your Basal Metabolic Rate (BMR) is the number of calories your body needs to function at rest. Our BMR Calculator uses the Mifflin-St Jeor equation to estimate this value. It also provides an estimate of your daily calorie needs based on your activity level to help you manage your weight." },
    { value: 'body-fat', label: 'Body Fat', path: '/personal-health-calculators', category: 'Health', icon: HeartPulse, keywords: ['health', 'fitness', 'physique'], description: "Estimate your body fat percentage using the U.S. Navy Method with our Body Fat Calculator. This tool uses measurements of your height, weight, neck, and waist (and hips for women) to provide a body fat estimate, your body fat category, and a breakdown of fat mass versus lean mass." },
    { value: 'calorie', label: 'Calorie', path: '/personal-health-calculators', category: 'Health', icon: HeartPulse, keywords: ['health', 'diet', 'macros', 'nutrition'], description: "Our Calorie & Macronutrient Calculator helps you create a personalized nutrition plan. Based on your age, gender, height, weight, activity level, and fitness goals, it estimates your daily calorie needs and provides a breakdown of carbohydrates, protein, and fat to help you achieve your desired results." },
    { value: 'creatinine-clearance', label: 'Creatinine Clearance', path: '/personal-health-calculators', category: 'Health', icon: HeartPulse, keywords: ['health', 'kidney', 'medical', 'crcl'], description: "The Creatinine Clearance (CrCl) Calculator estimates kidney function using the Cockcroft-Gault formula. This tool is intended for educational purposes, providing a CrCl value in mL/min based on age, weight, serum creatinine, and gender. Always consult a healthcare professional for medical advice." },
    { value: 'due-date', label: 'Due Date', path: '/personal-health-calculators', category: 'Health', icon: HeartPulse, keywords: ['health', 'pregnancy', 'baby'], description: "Our advanced Pregnancy Due Date Calculator does more than just estimate your due date. It provides a complete pregnancy timeline, including your current gestational age, trimester, and key developmental milestones. Powered by AI, it also offers weekly insights into your baby's development, changes for the mother, and answers to your specific pregnancy questions." },
    { value: 'egfr', label: 'eGFR', path: '/personal-health-calculators', category: 'Health', icon: HeartPulse, keywords: ['health', 'kidney', 'glomerular filtration rate'], description: "The Advanced eGFR Calculator uses the 2021 CKD-EPI equation to estimate Glomerular Filtration Rate, a key indicator of kidney function. By combining eGFR with the Urine Albumin-to-Creatinine Ratio (UACR), it also assesses your kidney disease prognosis based on KDIGO guidelines. This tool is for educational purposes only." },
    { value: 'heart-rate', label: 'Heart Rate', path: '/personal-health-calculators', category: 'Health', icon: HeartPulse, keywords: ['health', 'pulse', 'exercise', 'zones'], description: "Optimize your workouts with the Target Heart Rate Calculator. It estimates your maximum heart rate and defines five training zones, from 'Very Light' to 'Maximum,' helping you exercise at the right intensity for your goals. Additionally, you can analyze your resting heart rate to get an indication of your cardiovascular fitness level." },
    { value: 'ideal-weight', label: 'Ideal Weight', path: '/personal-health-calculators', category: 'Health', icon: HeartPulse, keywords: ['health', 'weight', 'fitness'], description: "Estimate your Ideal Body Weight using several popular scientific formulas (Robinson, Miller, Devine, Hamwi). Based on your height and gender, this calculator provides a healthy weight range and shows the results from each formula, giving you a comprehensive perspective on your weight goals." },
    { value: 'ovulation', label: 'Ovulation', path: '/personal-health-calculators', category: 'Health', icon: HeartPulse, keywords: ['health', 'fertility', 'cycle', 'pregnancy'], description: "Pinpoint your most fertile days with our Advanced Ovulation & Fertile Window Calculator. By tracking your menstrual cycle, it projects your fertile window, estimated ovulation day, and next period for the next six months. An interactive calendar visually highlights these key dates to help you plan." },

    // Date & Time
    { value: 'add-subtract-days', label: 'Add/Subtract Days', path: '/date-time-calculators', category: 'Date & Time', icon: CalendarDays, keywords: ['date', 'time', 'duration'], description: "Easily calculate a future or past date with the Add/Subtract Days and Time Calculator. Start with a specific date and time, then add or subtract any duration—from days down to seconds—to instantly find the resulting date and time, displayed on both a digital readout and an analog clock." },
    { value: 'time-calculator', label: 'Add/Subtract Time', path: '/date-time-calculators', category: 'Date & Time', icon: CalendarDays, keywords: ['date', 'time', 'duration'], description: "Manipulate time with precision using the Add/Subtract Time Calculator. This tool allows you to add or subtract hours, minutes, and seconds from a specified start time. The result is shown on a digital display and a dynamic analog clock, providing a clear visual representation of the time change." },
    { value: 'countdown', label: 'Countdown', path: '/date-time-calculators', category: 'Date & Time', icon: CalendarDays, keywords: ['date', 'time', 'timer', 'event'], description: "Set a timer for any future event with the Countdown Calculator. Pick a target date and time, and watch the live countdown, precise to the millisecond. The calculator features a unique sandbox animation for a visual representation of the time remaining and will play a sound and send a browser notification when the countdown ends." },
    { value: 'date-difference', label: 'Date Difference', path: '/date-time-calculators', category: 'Date & Time', icon: CalendarDays, keywords: ['date', 'time', 'duration', 'between'], description: "Quickly find the duration between two dates with the Date Difference Calculator. Select a start date and an end date, and the tool will instantly show you the total time elapsed, broken down into years, months, and days. It's perfect for calculating age or the duration of an event." },
    { value: 'workdays', label: 'Workdays (Simple)', path: '/date-time-calculators', category: 'Date & Time', icon: CalendarDays, keywords: ['date', 'time', 'business days', 'working'], description: "Plan your projects and schedules with the Workdays Calculator. This tool calculates the number of business days (Monday to Friday) between any two dates, excluding weekends. It's ideal for quick project management, tracking deadlines, or calculating business timelines." },
    { value: 'business-days', label: 'Business Days (Advanced)', path: '/date-time-calculators', category: 'Date & Time', icon: CalendarDays, keywords: ['date', 'time', 'business days', 'working', 'holiday', 'timezone'], description: "Calculate the number of working days between two dates across different time zones. Our Advanced Business Days Calculator accounts for local public holidays and weekends, providing an accurate count for international planning and project management. Compare multiple time zones side-by-side to understand how holidays impact your timeline." },
    { value: 'time-zone', label: 'Time Zone', path: '/date-time-calculators', category: 'Date & Time', icon: CalendarDays, keywords: ['date', 'time', 'timezone', 'gmt', 'utc', 'daylight savings'], description: "Navigate global time with our powerful Time Zone Tools. Use the World Clock to compare multiple time zones at once on a live, interactive dashboard, or use the Converter to find the exact corresponding time for a specific event. The tool automatically handles Daylight Saving Time (DST) and shows GMT offsets for full accuracy." },

    // Math & Science
    { value: 'algebra', label: 'Algebra', path: '/math-science-calculators', category: 'Math & Science', icon: BrainCircuit, keywords: ['math', 'equation', 'linear', 'quadratic'], description: "Solve common algebraic problems with the Algebra Calculator. This versatile tool can handle linear equations (ax + b = c), quadratic equations (ax² + bx + c = 0), and systems of two linear equations, providing clear solutions for x and y." },
    { value: 'basic', label: 'Basic', path: '/math-science-calculators', category: 'Math & Science', icon: BrainCircuit, keywords: ['math', 'arithmetic'], description: "Perform everyday calculations with our simple and intuitive Basic Calculator. It features a clean interface with a running display of your expression and supports all standard arithmetic operations, including addition, subtraction, multiplication, and division, as well as percentage and sign change functions." },
    { value: 'break-even', label: 'Break-Even', path: '/math-science-calculators', category: 'Math & Science', icon: BrainCircuit, keywords: ['business', 'finance', 'profit'], description: "Find the point where your revenue equals your costs with the Break-Even Point Calculator. By entering your total fixed costs, variable cost per unit, and selling price per unit, this tool determines how many units you need to sell to cover all your expenses, providing the result in both units and total revenue." },
    { value: 'chemistry', label: 'Chemistry', path: '/math-science-calculators', category: 'Math & Science', icon: BrainCircuit, keywords: ['science', 'molarity', 'molecular weight'], description: "Our Chemistry Calculator simplifies common chemical calculations. Use it to find the molarity of a solution by providing the moles of solute and volume of the solution, or calculate the molecular weight of a compound by simply entering its chemical formula (e.g., H2O or C6H12O6)." },
    { value: 'chemistry-solver', label: 'Chemistry AI Solver', path: '/math-science-calculators', category: 'Math & Science', icon: BrainCircuit, keywords: ['science', 'ai', 'stoichiometry', 'solution'], description: "Stuck on a chemistry problem? Our AI Chemistry Problem Solver provides detailed, step-by-step solutions. Just type in your question, and the AI will identify the problem type, list relevant formulas, provide a conceptual overview, and walk you through to the final answer. It's like having a virtual chemistry professor." },
    { value: 'discount', label: 'Discount', path: '/math-science-calculators', category: 'Math & Science', icon: BrainCircuit, keywords: ['math', 'sale', 'percentage'], description: "Instantly calculate the final price of an item after a discount with our Discount Calculator. Enter the original price and the discount percentage to find out how much you save and what the new price will be. It's the perfect shopping companion." },
    { value: 'fraction', label: 'Fraction', path: '/math-science-calculators', category: 'Math & Science', icon: BrainCircuit, keywords: ['math', 'arithmetic'], description: "Perform arithmetic operations on fractions with ease using the Fraction Calculator. It allows you to add, subtract, multiply, and divide two fractions. The calculator automatically simplifies the result to its lowest terms, providing a clear and accurate answer." },
    { value: 'geometry', label: 'Geometry', path: '/math-science-calculators', category: 'Math & Science', icon: BrainCircuit, keywords: ['math', 'shape', 'area', 'volume'], description: "Solve for the properties of common geometric shapes with our Geometry Calculator. Quickly find the area and perimeter of rectangles, the area and circumference of circles, the area of triangles, and the volume and surface area of cubes." },
    { value: 'graphing', label: 'Graphing', path: '/math-science-calculators', category: 'Math & Science', icon: BrainCircuit, keywords: ['math', 'plot', 'function', 'equation'], description: "Visualize mathematical functions with the Graphing Calculator. Enter an expression in terms of 'x' (e.g., x^2 - 3*x + 5), define the range (X Min, X Max), and see it plotted on an interactive chart. It's a great tool for students and professionals to understand complex functions." },
    { value: 'markup-margin', label: 'Markup & Margin', path: '/math-science-calculators', category: 'Math & Science', icon: BrainCircuit, keywords: ['business', 'finance', 'profit'], description: "Understand your business profitability with the Markup & Margin Calculator. By entering the cost and revenue for a product, this tool instantly calculates your gross profit, gross margin percentage, and markup percentage, providing key insights into your pricing strategy." },
    { value: 'percentage', label: 'Percentage', path: '/math-science-calculators', category: 'Math & Science', icon: BrainCircuit, keywords: ['math', 'percent'], description: "Solve a variety of percentage-related problems with our versatile Percentage Calculator. It has three modes: find what 'X% of Y' is, calculate 'X is what % of Y', and determine the percentage increase or decrease from one value to another." },
    { value: 'physics', label: 'Physics', path: '/math-science-calculators', category: 'Math & Science', icon: BrainCircuit, keywords: ['science', 'force', 'energy', 'speed'], description: "Tackle fundamental physics problems with our Physics Calculator. It includes modules to calculate speed (from distance and time), force (using Newton's second law, F=ma), and energy (both kinetic and potential energy), making it a handy tool for students and enthusiasts." },
    { value: 'scientific', label: 'Scientific', path: '/math-science-calculators', category: 'Math & Science', icon: BrainCircuit, keywords: ['math', 'log', 'sin', 'cos'], description: "Our Scientific Calculator is designed for more complex mathematical tasks. It supports trigonometric functions (sin, cos, tan) and their inverses, logarithms (natural, log10, log2), powers, roots, factorials, and constants like π and e, all in an easy-to-use interface." },
    { value: 'unit', label: 'Unit Converter', path: '/math-science-calculators', category: 'Math & Science', icon: BrainCircuit, keywords: ['conversion', 'length', 'weight', 'volume'], description: "The Unit Converter is an essential tool for converting between various units of measurement. It supports conversions for length (meters, feet, miles), weight (grams, pounds), volume (liters, gallons), and temperature (Celsius, Fahrenheit, Kelvin), making it useful for a wide range of applications." },

    // Other
    { value: 'bsa', label: 'Body Surface Area', path: '/other-specialized-calculators', category: 'Other', icon: Sparkles, keywords: ['medical', 'health', 'bsa'], description: "The Body Surface Area (BSA) Calculator estimates the total surface area of the human body. It uses the Du Bois formula, a common method in clinical practice for determining medication dosages. This tool is for educational purposes only; always consult a healthcare professional for medical advice." },
    { value: 'carbon-footprint', label: 'Carbon Footprint', path: '/other-specialized-calculators', category: 'Other', icon: Sparkles, keywords: ['environment', 'climate', 'co2'], description: "Estimate your environmental impact with our Carbon Footprint Calculator. Based on your monthly electricity usage, transportation habits (vehicle mileage and flights), and household waste, this tool provides an estimate of your annual carbon footprint in kilograms of CO₂ equivalent." },
    { value: 'cooking-converter', label: 'Cooking Converter', path: '/other-specialized-calculators', category: 'Other', icon: Sparkles, keywords: ['food', 'recipe', 'measurement'], description: "The Cooking Measurement Converter is a must-have tool for any kitchen. Easily convert between common cooking units for volume (like cups, tablespoons, and milliliters) and weight (like grams, ounces, and pounds) to get your recipes just right." },
    { value: 'fuel-efficiency', label: 'Fuel Efficiency', path: '/other-specialized-calculators', category: 'Other', icon: Sparkles, keywords: ['car', 'vehicle', 'mpg', 'gas'], description: "Calculate your vehicle's fuel economy with the Fuel Efficiency Calculator. Enter the distance you've traveled and the amount of fuel consumed to find out your efficiency in both miles per gallon (MPG) and kilometers per liter (KM/L)." },
    { value: 'gpa', label: 'GPA', path: '/other-specialized-calculators', category: 'Other', icon: Sparkles, keywords: ['education', 'school', 'college', 'grades'], description: "Track your academic performance with our GPA Calculator. Add your courses, enter the grade you received and the number of credits for each, and the tool will calculate your Grade Point Average (GPA) for the semester or your entire academic career." },
    { value: 'loan-eligibility', label: 'Loan Eligibility', path: '/other-specialized-calculators', category: 'Other', icon: Sparkles, keywords: ['finance', 'credit', 'approval'], description: "Find out if you're likely to be approved for a loan with our AI Loan Eligibility Calculator. By analyzing your monthly income, expenses, credit score, and desired loan terms, this tool provides an eligibility status (Eligible, Provisional, or Not Eligible), an estimated eligible loan amount, and a detailed analysis of the decision." },
];
