
export const timezoneInfo: Record<string, { countryCode: string; countryName: string; }> = {
    "Europe/Andorra": { "countryCode": "AD", "countryName": "Andorra" },
    "Asia/Dubai": { "countryCode": "AE", "countryName": "United Arab Emirates" },
    "Asia/Kabul": { "countryCode": "AF", "countryName": "Afghanistan" },
    "America/Antigua": { "countryCode": "AG", "countryName": "Antigua and Barbuda" },
    "America/Anguilla": { "countryCode": "AI", "countryName": "Anguilla" },
    "Europe/Tirane": { "countryCode": "AL", "countryName": "Albania" },
    "Asia/Yerevan": { "countryCode": "AM", "countryName": "Armenia" },
    "Africa/Luanda": { "countryCode": "AO", "countryName": "Angola" },
    "Antarctica/McMurdo": { "countryCode": "AQ", "countryName": "Antarctica" },
    "America/Argentina/Buenos_Aires": { "countryCode": "AR", "countryName": "Argentina" },
    "Pacific/Pago_Pago": { "countryCode": "AS", "countryName": "American Samoa" },
    "Europe/Vienna": { "countryCode": "AT", "countryName": "Austria" },
    "Australia/Sydney": { "countryCode": "AU", "countryName": "Australia" },
    "America/Aruba": { "countryCode": "AW", "countryName": "Aruba" },
    "Europe/Mariehamn": { "countryCode": "AX", "countryName": "Åland Islands" },
    "Asia/Baku": { "countryCode": "AZ", "countryName": "Azerbaijan" },
    "Europe/Sarajevo": { "countryCode": "BA", "countryName": "Bosnia and Herzegovina" },
    "America/Barbados": { "countryCode": "BB", "countryName": "Barbados" },
    "Asia/Dhaka": { "countryCode": "BD", "countryName": "Bangladesh" },
    "Europe/Brussels": { "countryCode": "BE", "countryName": "Belgium" },
    "Africa/Ouagadougou": { "countryCode": "BF", "countryName": "Burkina Faso" },
    "Europe/Sofia": { "countryCode": "BG", "countryName": "Bulgaria" },
    "Asia/Bahrain": { "countryCode": "BH", "countryName": "Bahrain" },
    "Africa/Bujumbura": { "countryCode": "BI", "countryName": "Burundi" },
    "Africa/Porto-Novo": { "countryCode": "BJ", "countryName": "Benin" },
    "America/St_Barthelemy": { "countryCode": "BL", "countryName": "St. Barthélemy" },
    "Atlantic/Bermuda": { "countryCode": "BM", "countryName": "Bermuda" },
    "Asia/Brunei": { "countryCode": "BN", "countryName": "Brunei" },
    "America/La_Paz": { "countryCode": "BO", "countryName": "Bolivia" },
    "America/Sao_Paulo": { "countryCode": "BR", "countryName": "Brazil" },
    "America/Nassau": { "countryCode": "BS", "countryName": "Bahamas" },
    "Asia/Thimphu": { "countryCode": "BT", "countryName": "Bhutan" },
    "Africa/Gaborone": { "countryCode": "BW", "countryName": "Botswana" },
    "Europe/Minsk": { "countryCode": "BY", "countryName": "Belarus" },
    "America/Belize": { "countryCode": "BZ", "countryName": "Belize" },
    "America/Toronto": { "countryCode": "CA", "countryName": "Canada" },
    "Indian/Cocos": { "countryCode": "CC", "countryName": "Cocos (Keeling) Islands" },
    "Africa/Kinshasa": { "countryCode": "CD", "countryName": "Congo (DRC)" },
    "Africa/Bangui": { "countryCode": "CF", "countryName": "Central African Republic" },
    "Africa/Brazzaville": { "countryCode": "CG", "countryName": "Congo" },
    "Europe/Zurich": { "countryCode": "CH", "countryName": "Switzerland" },
    "Africa/Abidjan": { "countryCode": "CI", "countryName": "Côte d’Ivoire" },
    "Pacific/Rarotonga": { "countryCode": "CK", "countryName": "Cook Islands" },
    "America/Santiago": { "countryCode": "CL", "countryName": "Chile" },
    "Africa/Douala": { "countryCode": "CM", "countryName": "Cameroon" },
    "Asia/Shanghai": { "countryCode": "CN", "countryName": "China" },
    "America/Bogota": { "countryCode": "CO", "countryName": "Colombia" },
    "America/Costa_Rica": { "countryCode": "CR", "countryName": "Costa Rica" },
    "America/Havana": { "countryCode": "CU", "countryName": "Cuba" },
    "Atlantic/Cape_Verde": { "countryCode": "CV", "countryName": "Cape Verde" },
    "America/Curacao": { "countryCode": "CW", "countryName": "Curaçao" },
    "Indian/Christmas": { "countryCode": "CX", "countryName": "Christmas Island" },
    "Asia/Nicosia": { "countryCode": "CY", "countryName": "Cyprus" },
    "Europe/Prague": { "countryCode": "CZ", "countryName": "Czech Republic" },
    "Europe/Berlin": { "countryCode": "DE", "countryName": "Germany" },
    "Africa/Djibouti": { "countryCode": "DJ", "countryName": "Djibouti" },
    "Europe/Copenhagen": { "countryCode": "DK", "countryName": "Denmark" },
    "America/Dominica": { "countryCode": "DM", "countryName": "Dominica" },
    "America/Santo_Domingo": { "countryCode": "DO", "countryName": "Dominican Republic" },
    "Africa/Algiers": { "countryCode": "DZ", "countryName": "Algeria" },
    "America/Guayaquil": { "countryCode": "EC", "countryName": "Ecuador" },
    "Europe/Tallinn": { "countryCode": "EE", "countryName": "Estonia" },
    "Africa/Cairo": { "countryCode": "EG", "countryName": "Egypt" },
    "Africa/El_Aaiun": { "countryCode": "EH", "countryName": "Western Sahara" },
    "Africa/Asmara": { "countryCode": "ER", "countryName": "Eritrea" },
    "Europe/Madrid": { "countryCode": "ES", "countryName": "Spain" },
    "Africa/Addis_Ababa": { "countryCode": "ET", "countryName": "Ethiopia" },
    "Europe/Helsinki": { "countryCode": "FI", "countryName": "Finland" },
    "Pacific/Fiji": { "countryCode": "FJ", "countryName": "Fiji" },
    "Atlantic/Stanley": { "countryCode": "FK", "countryName": "Falkland Islands" },
    "Pacific/Chuuk": { "countryCode": "FM", "countryName": "Micronesia" },
    "Atlantic/Faroe": { "countryCode": "FO", "countryName": "Faroe Islands" },
    "Europe/Paris": { "countryCode": "FR", "countryName": "France" },
    "Africa/Libreville": { "countryCode": "GA", "countryName": "Gabon" },
    "Europe/London": { "countryCode": "GB", "countryName": "United Kingdom" },
    "America/Grenada": { "countryCode": "GD", "countryName": "Grenada" },
    "Asia/Tbilisi": { "countryCode": "GE", "countryName": "Georgia" },
    "America/Cayenne": { "countryCode": "GF", "countryName": "French Guiana" },
    "Europe/Guernsey": { "countryCode": "GG", "countryName": "Guernsey" },
    "Africa/Accra": { "countryCode": "GH", "countryName": "Ghana" },
    "Europe/Gibraltar": { "countryCode": "GI", "countryName": "Gibraltar" },
    "America/Godthab": { "countryCode": "GL", "countryName": "Greenland" },
    "Africa/Banjul": { "countryCode": "GM", "countryName": "Gambia" },
    "Africa/Conakry": { "countryCode": "GN", "countryName": "Guinea" },
    "America/Guadeloupe": { "countryCode": "GP", "countryName": "Guadeloupe" },
    "Africa/Malabo": { "countryCode": "GQ", "countryName": "Equatorial Guinea" },
    "Europe/Athens": { "countryCode": "GR", "countryName": "Greece" },
    "Atlantic/South_Georgia": { "countryCode": "GS", "countryName": "South Georgia & South Sandwich Islands" },
    "America/Guatemala": { "countryCode": "GT", "countryName": "Guatemala" },
    "Pacific/Guam": { "countryCode": "GU", "countryName": "Guam" },
    "Africa/Bissau": { "countryCode": "GW", "countryName": "Guinea-Bissau" },
    "America/Guyana": { "countryCode": "GY", "countryName": "Guyana" },
    "Asia/Hong_Kong": { "countryCode": "HK", "countryName": "Hong Kong" },
    "America/Tegucigalpa": { "countryCode": "HN", "countryName": "Honduras" },
    "Europe/Zagreb": { "countryCode": "HR", "countryName": "Croatia" },
    "America/Port-au-Prince": { "countryCode": "HT", "countryName": "Haiti" },
    "Europe/Budapest": { "countryCode": "HU", "countryName": "Hungary" },
    "Asia/Jakarta": { "countryCode": "ID", "countryName": "Indonesia" },
    "Europe/Dublin": { "countryCode": "IE", "countryName": "Ireland" },
    "Asia/Jerusalem": { "countryCode": "IL", "countryName": "Israel" },
    "Europe/Isle_of_Man": { "countryCode": "IM", "countryName": "Isle of Man" },
    "Asia/Kolkata": { "countryCode": "IN", "countryName": "India" },
    "Indian/Chagos": { "countryCode": "IO", "countryName": "British Indian Ocean Territory" },
    "Asia/Baghdad": { "countryCode": "IQ", "countryName": "Iraq" },
    "Asia/Tehran": { "countryCode": "IR", "countryName": "Iran" },
    "Atlantic/Reykjavik": { "countryCode": "IS", "countryName": "Iceland" },
    "Europe/Rome": { "countryCode": "IT", "countryName": "Italy" },
    "Europe/Jersey": { "countryCode": "JE", "countryName": "Jersey" },
    "America/Jamaica": { "countryCode": "JM", "countryName": "Jamaica" },
    "Asia/Amman": { "countryCode": "JO", "countryName": "Jordan" },
    "Asia/Tokyo": { "countryCode": "JP", "countryName": "Japan" },
    "Africa/Nairobi": { "countryCode": "KE", "countryName": "Kenya" },
    "Asia/Bishkek": { "countryCode": "KG", "countryName": "Kyrgyzstan" },
    "Asia/Phnom_Penh": { "countryCode": "KH", "countryName": "Cambodia" },
    "Pacific/Tarawa": { "countryCode": "KI", "countryName": "Kiribati" },
    "Indian/Comoro": { "countryCode": "KM", "countryName": "Comoros" },
    "America/St_Kitts": { "countryCode": "KN", "countryName": "St. Kitts & Nevis" },
    "Asia/Pyongyang": { "countryCode": "KP", "countryName": "North Korea" },
    "Asia/Seoul": { "countryCode": "KR", "countryName": "South Korea" },
    "Asia/Kuwait": { "countryCode": "KW", "countryName": "Kuwait" },
    "America/Cayman": { "countryCode": "KY", "countryName": "Cayman Islands" },
    "Asia/Almaty": { "countryCode": "KZ", "countryName": "Kazakhstan" },
    "Asia/Vientiane": { "countryCode": "LA", "countryName": "Laos" },
    "Asia/Beirut": { "countryCode": "LB", "countryName": "Lebanon" },
    "America/St_Lucia": { "countryCode": "LC", "countryName": "St. Lucia" },
    "Europe/Vaduz": { "countryCode": "LI", "countryName": "Liechtenstein" },
    "Asia/Colombo": { "countryCode": "LK", "countryName": "Sri Lanka" },
    "Africa/Monrovia": { "countryCode": "LR", "countryName": "Liberia" },
    "Africa/Maseru": { "countryCode": "LS", "countryName": "Lesotho" },
    "Europe/Vilnius": { "countryCode": "LT", "countryName": "Lithuania" },
    "Europe/Luxembourg": { "countryCode": "LU", "countryName": "Luxembourg" },
    "Europe/Riga": { "countryCode": "LV", "countryName": "Latvia" },
    "Africa/Tripoli": { "countryCode": "LY", "countryName": "Libya" },
    "Africa/Casablanca": { "countryCode": "MA", "countryName": "Morocco" },
    "Europe/Monaco": { "countryCode": "MC", "countryName": "Monaco" },
    "Europe/Chisinau": { "countryCode": "MD", "countryName": "Moldova" },
    "Europe/Podgorica": { "countryCode": "ME", "countryName": "Montenegro" },
    "America/Marigot": { "countryCode": "MF", "countryName": "St. Martin" },
    "Indian/Antananarivo": { "countryCode": "MG", "countryName": "Madagascar" },
    "Pacific/Majuro": { "countryCode": "MH", "countryName": "Marshall Islands" },
    "Europe/Skopje": { "countryCode": "MK", "countryName": "North Macedonia" },
    "Africa/Bamako": { "countryCode": "ML", "countryName": "Mali" },
    "Asia/Yangon": { "countryCode": "MM", "countryName": "Myanmar (Burma)" },
    "Asia/Ulaanbaatar": { "countryCode": "MN", "countryName": "Mongolia" },
    "Asia/Macau": { "countryCode": "MO", "countryName": "Macau" },
    "Pacific/Saipan": { "countryCode": "MP", "countryName": "Northern Mariana Islands" },
    "America/Martinique": { "countryCode": "MQ", "countryName": "Martinique" },
    "Africa/Nouakchott": { "countryCode": "MR", "countryName": "Mauritania" },
    "America/Montserrat": { "countryCode": "MS", "countryName": "Montserrat" },
    "Europe/Malta": { "countryCode": "MT", "countryName": "Malta" },
    "Indian/Mauritius": { "countryCode": "MU", "countryName": "Mauritius" },
    "Indian/Maldives": { "countryCode": "MV", "countryName": "Maldives" },
    "Africa/Blantyre": { "countryCode": "MW", "countryName": "Malawi" },
    "America/Mexico_City": { "countryCode": "MX", "countryName": "Mexico" },
    "Asia/Kuala_Lumpur": { "countryCode": "MY", "countryName": "Malaysia" },
    "Africa/Maputo": { "countryCode": "MZ", "countryName": "Mozambique" },
    "Africa/Windhoek": { "countryCode": "NA", "countryName": "Namibia" },
    "Pacific/Noumea": { "countryCode": "NC", "countryName": "New Caledonia" },
    "Africa/Niamey": { "countryCode": "NE", "countryName": "Niger" },
    "Pacific/Norfolk": { "countryCode": "NF", "countryName": "Norfolk Island" },
    "Africa/Lagos": { "countryCode": "NG", "countryName": "Nigeria" },
    "America/Managua": { "countryCode": "NI", "countryName": "Nicaragua" },
    "Europe/Amsterdam": { "countryCode": "NL", "countryName": "Netherlands" },
    "Europe/Oslo": { "countryCode": "NO", "countryName": "Norway" },
    "Asia/Kathmandu": { "countryCode": "NP", "countryName": "Nepal" },
    "Pacific/Nauru": { "countryCode": "NR", "countryName": "Nauru" },
    "Pacific/Niue": { "countryCode": "NU", "countryName": "Niue" },
    "Pacific/Auckland": { "countryCode": "NZ", "countryName": "New Zealand" },
    "Asia/Muscat": { "countryCode": "OM", "countryName": "Oman" },
    "America/Panama": { "countryCode": "PA", "countryName": "Panama" },
    "America/Lima": { "countryCode": "PE", "countryName": "Peru" },
    "Pacific/Tahiti": { "countryCode": "PF", "countryName": "French Polynesia" },
    "Pacific/Port_Moresby": { "countryCode": "PG", "countryName": "Papua New Guinea" },
    "Asia/Manila": { "countryCode": "PH", "countryName": "Philippines" },
    "Asia/Karachi": { "countryCode": "PK", "countryName": "Pakistan" },
    "Europe/Warsaw": { "countryCode": "PL", "countryName": "Poland" },
    "America/Miquelon": { "countryCode": "PM", "countryName": "St. Pierre & Miquelon" },
    "Pacific/Pitcairn": { "countryCode": "PN", "countryName": "Pitcairn Islands" },
    "America/Puerto_Rico": { "countryCode": "PR", "countryName": "Puerto Rico" },
    "Asia/Gaza": { "countryCode": "PS", "countryName": "Palestine" },
    "Europe/Lisbon": { "countryCode": "PT", "countryName": "Portugal" },
    "Pacific/Palau": { "countryCode": "PW", "countryName": "Palau" },
    "America/Asuncion": { "countryCode": "PY", "countryName": "Paraguay" },
    "Asia/Qatar": { "countryCode": "QA", "countryName": "Qatar" },
    "Indian/Reunion": { "countryCode": "RE", "countryName": "Réunion" },
    "Europe/Bucharest": { "countryCode": "RO", "countryName": "Romania" },
    "Europe/Belgrade": { "countryCode": "RS", "countryName": "Serbia" },
    "Europe/Moscow": { "countryCode": "RU", "countryName": "Russia" },
    "Africa/Kigali": { "countryCode": "RW", "countryName": "Rwanda" },
    "Asia/Riyadh": { "countryCode": "SA", "countryName": "Saudi Arabia" },
    "Pacific/Guadalcanal": { "countryCode": "SB", "countryName": "Solomon Islands" },
    "Indian/Mahe": { "countryCode": "SC", "countryName": "Seychelles" },
    "Africa/Khartoum": { "countryCode": "SD", "countryName": "Sudan" },
    "Europe/Stockholm": { "countryCode": "SE", "countryName": "Sweden" },
    "Asia/Singapore": { "countryCode": "SG", "countryName": "Singapore" },
    "Atlantic/St_Helena": { "countryCode": "SH", "countryName": "St. Helena" },
    "Europe/Ljubljana": { "countryCode": "SI", "countryName": "Slovenia" },
    "Arctic/Longyearbyen": { "countryCode": "SJ", "countryName": "Svalbard & Jan Mayen" },
    "Europe/Bratislava": { "countryCode": "SK", "countryName": "Slovakia" },
    "Africa/Freetown": { "countryCode": "SL", "countryName": "Sierra Leone" },
    "Europe/San_Marino": { "countryCode": "SM", "countryName": "San Marino" },
    "Africa/Dakar": { "countryCode": "SN", "countryName": "Senegal" },
    "Africa/Mogadishu": { "countryCode": "SO", "countryName": "Somalia" },
    "America/Paramaribo": { "countryCode": "SR", "countryName": "Suriname" },
    "Africa/Juba": { "countryCode": "SS", "countryName": "South Sudan" },
    "Africa/Sao_Tome": { "countryCode": "ST", "countryName": "São Tomé & Príncipe" },
    "America/El_Salvador": { "countryCode": "SV", "countryName": "El Salvador" },
    "America/Lower_Princes": { "countryCode": "SX", "countryName": "Sint Maarten" },
    "Asia/Damascus": { "countryCode": "SY", "countryName": "Syria" },
    "Africa/Mbabane": { "countryCode": "SZ", "countryName": "Eswatini" },
    "America/Grand_Turk": { "countryCode": "TC", "countryName": "Turks & Caicos Islands" },
    "Africa/Ndjamena": { "countryCode": "TD", "countryName": "Chad" },
    "Indian/Kerguelen": { "countryCode": "TF", "countryName": "French Southern Territories" },
    "Africa/Lome": { "countryCode": "TG", "countryName": "Togo" },
    "Asia/Bangkok": { "countryCode": "TH", "countryName": "Thailand" },
    "Asia/Dushanbe": { "countryCode": "TJ", "countryName": "Tajikistan" },
    "Pacific/Fakaofo": { "countryCode": "TK", "countryName": "Tokelau" },
    "Asia/Dili": { "countryCode": "TL", "countryName": "Timor-Leste" },
    "Asia/Ashgabat": { "countryCode": "TM", "countryName": "Turkmenistan" },
    "Africa/Tunis": { "countryCode": "TN", "countryName": "Tunisia" },
    "Pacific/Tongatapu": { "countryCode": "TO", "countryName": "Tonga" },
    "Europe/Istanbul": { "countryCode": "TR", "countryName": "Turkey" },
    "America/Port_of_Spain": { "countryCode": "TT", "countryName": "Trinidad & Tobago" },
    "Pacific/Funafuti": { "countryCode": "TV", "countryName": "Tuvalu" },
    "Asia/Taipei": { "countryCode": "TW", "countryName": "Taiwan" },
    "Africa/Dar_es_Salaam": { "countryCode": "TZ", "countryName": "Tanzania" },
    "Europe/Kiev": { "countryCode": "UA", "countryName": "Ukraine" },
    "Africa/Kampala": { "countryCode": "UG", "countryName": "Uganda" },
    "America/New_York": { "countryCode": "US", "countryName": "United States" },
    "America/Montevideo": { "countryCode": "UY", "countryName": "Uruguay" },
    "Asia/Samarkand": { "countryCode": "UZ", "countryName": "Uzbekistan" },
    "Europe/Vatican": { "countryCode": "VA", "countryName": "Vatican City" },
    "America/St_Vincent": { "countryCode": "VC", "countryName": "St. Vincent & Grenadines" },
    "America/Caracas": { "countryCode": "VE", "countryName": "Venezuela" },
    "America/Tortola": { "countryCode": "VG", "countryName": "British Virgin Islands" },
    "America/St_Thomas": { "countryCode": "VI", "countryName": "U.S. Virgin Islands" },
    "Asia/Ho_Chi_Minh": { "countryCode": "VN", "countryName": "Vietnam" },
    "Pacific/Efate": { "countryCode": "VU", "countryName": "Vanuatu" },
    "Pacific/Wallis": { "countryCode": "WF", "countryName": "Wallis & Futuna" },
    "Pacific/Apia": { "countryCode": "WS", "countryName": "Samoa" },
    "Asia/Aden": { "countryCode": "YE", "countryName": "Yemen" },
    "Indian/Mayotte": { "countryCode": "YT", "countryName": "Mayotte" },
    "Africa/Johannesburg": { "countryCode": "ZA", "countryName": "South Africa" },
    "Africa/Lusaka": { "countryCode": "ZM", "countryName": "Zambia" },
    "Africa/Harare": { "countryCode": "ZW", "countryName": "Zimbabwe" },
}
